name: "Bug Report"
description: "Use this template to report a bug encountered in the portfolio repository."
title: "bug: <brief description>"
labels: ["bug"]
assignees:
  - "mrasadatik"
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Provide a detailed description of the bug, including what you were doing or exploring when the issue occurred."
    validations:
      required: false
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "Steps to reproduce the behavior."
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment
      placeholder: |
        - OS: Ubuntu 20.04
        - Node: 13.14.0
        - npm: 7.6.3
    validations:
      required: false
  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected Behavior"
      description: "Clearly describe what you expected to happen."
    validations:
      required: false
  - type: textarea
    id: actual_behavior
    attributes:
      label: "Actual Behavior"
      description: "Explain what actually happens when the bug occurs."
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: "If applicable, include screenshots, error messages, or logs to help illustrate the problem."
    validations:
      required: false
  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Share any other relevant information about the bug."
    validations:
      required: false
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: "Before submitting your bug report, please ensure you have:"
      options:
        - label: "Checked if the issue already exists in the Issues tab."
        - label: "Verified that the bug occurs consistently under the provided steps."
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## Contact
        This repository is owned and maintained by **Md Asaduzzaman Atik**. If you have any questions or need further assistance, please reach out via:
        - **Casual Conversations:**  
          **Email:** [hey@mr.asadatik.dev](mailto:hey@mr.asadatik.dev)  
          For informal discussions, brainstorming, or sharing ideas.
        - **Professional Conversations & Networking:**  
          **Email:** [engage@mr.asadatik.dev](mailto:engage@mr.asadatik.dev)  
          For business discussions, networking, or professional opportunities.
        - **Career Development & Collaboration:**  
          **Email:** [flow@mr.asadatik.dev](mailto:flow@mr.asadatik.dev)  
          To discuss career paths, collaboration opportunities, or new projects.
        - **Support & Troubleshooting:**  
          **Email:** [help@mr.asadatik.dev](mailto:help@mr.asadatik.dev)  
          For project-related issues or technical support inquiries — I'm here to assist.
