blank_issues_enabled: false
contact_links:
  - name: "Email: Support & Troubleshooting"
    url: mailto:help@mr.asadatik.dev
    about: For project-related issues or technical support inquiries — I'm here to assist.
