name: "General Task"
description: "Use this template to outline a task that needs to be completed in the portfolio repository. This can include non-issue-related tasks, refactoring, updates, or any other type of work."
title: "general: <brief description of the task>"
labels: ["general"]
assignees:
  - "mrasadatik"
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Provide a detailed description of the task. Explain its purpose, importance, and any relevant context or background information."
    validations:
      required: false
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: "Acceptance Criteria"
      description: "List the criteria that need to be met for the task to be considered complete."
    validations:
      required: false
  - type: textarea
    id: dependencies
    attributes:
      label: "Dependencies"
      description: "If this task depends on any other tasks or issues, please specify them here and include links if applicable."
    validations:
      required: false
  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Add any other relevant information or context that may help in completing the task effectively."
    validations:
      required: false
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: "Before submitting your task, please ensure you have:"
      options:
        - label: "Verified that the task aligns with the repository's goals."
        - label: "Checked the Issues tab to ensure a similar task hasn't already been submitted."
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## Contact
        This repository is owned and maintained by **Md Asaduzzaman Atik**. If you have any questions or need further assistance, please reach out via:
        - **Casual Conversations:**  
          **Email:** [hey@mr.asadatik.dev](mailto:hey@mr.asadatik.dev)  
          For informal discussions, brainstorming, or sharing ideas.
        - **Professional Conversations & Networking:**  
          **Email:** [engage@mr.asadatik.dev](mailto:engage@mr.asadatik.dev)  
          For business discussions, networking, or professional opportunities.
        - **Career Development & Collaboration:**  
          **Email:** [flow@mr.asadatik.dev](mailto:flow@mr.asadatik.dev)  
          To discuss career paths, collaboration opportunities, or new projects.
        - **Support & Troubleshooting:**  
          **Email:** [help@mr.asadatik.dev](mailto:help@mr.asadatik.dev)  
          For project-related issues or technical support inquiries — I'm here to assist.
