name: "Performance Issue"
description: "Use this template to report a performance-related issue encountered in the portfolio repository."
title: "performance: <brief description>"
labels: ["performance", "perf"]
assignees:
  - "mrasadatik"
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Provide a detailed description of the performance issue, including what you were trying to accomplish when the issue occurred."
    validations:
      required: false
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "Steps to reproduce the behavior."
      placeholder: |
        1. Step one
        2. Step two
        3. Step three
    validations:
      required: false
  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected Behavior"
      description: "Clearly describe what you expected to happen in terms of performance (e.g., faster load times, lower memory usage)."
    validations:
      required: false
  - type: textarea
    id: actual_behavior
    attributes:
      label: "Actual Behavior"
      description: "Describe what actually happens, including any metrics or indicators of poor performance (e.g., slow load times, high latency)."
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: "If applicable, include screenshots or error messages that help illustrate the performance issue."
    validations:
      required: false
  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Add any other relevant information that might assist in diagnosing the problem, such as environment details, system configurations, or related issues."
    validations:
      required: false
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: "Before submitting your performance issue report, please ensure you have:"
      options:
        - label: "Checked the Issues tab to ensure this performance issue hasn't already been reported."
        - label: "Reviewed the repository's guidelines to align with its goals and standards."
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## Contact
        This repository is owned and maintained by **Md Asaduzzaman Atik**. If you have any questions or need further assistance, please reach out via:
        - **Casual Conversations:**  
          **Email:** [hey@mr.asadatik.dev](mailto:hey@mr.asadatik.dev)  
          For informal discussions, brainstorming, or sharing ideas.
        - **Professional Conversations & Networking:**  
          **Email:** [engage@mr.asadatik.dev](mailto:engage@mr.asadatik.dev)  
          For business discussions, networking, or professional opportunities.
        - **Career Development & Collaboration:**  
          **Email:** [flow@mr.asadatik.dev](mailto:flow@mr.asadatik.dev)  
          To discuss career paths, collaboration opportunities, or new projects.
        - **Support & Troubleshooting:**  
          **Email:** [help@mr.asadatik.dev](mailto:help@mr.asadatik.dev)  
          For project-related issues or technical support inquiries — I'm here to assist.
