name: "Security Vulnerability Report"
description: "Use this template to report a security vulnerability within the portfolio repository. Responsible disclosure ensures the security and integrity of the repository."
title: "security: <brief description of the vulnerability>"
labels: ["security"]
assignees:
  - "mrasadatik"
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Provide a detailed description of the security vulnerability, including its potential impact and severity."
    validations:
      required: false
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "Steps to reproduce the vulnerability."
      placeholder: |
        1. Step one
        2. Step two
        3. Step three
    validations:
      required: false
  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected Behavior"
      description: "Describe what should happen without the vulnerability."
    validations:
      required: false
  - type: textarea
    id: actual_behavior
    attributes:
      label: "Actual Behavior"
      description: "Describe what happens due to the vulnerability."
    validations:
      required: false
  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Include any additional information that may be relevant, such as configurations, versions affected, or related vulnerabilities."
    validations:
      required: false
  - type: textarea
    id: suggested_mitigation
    attributes:
      label: "Suggested Mitigation"
      description: "If applicable, provide any suggestions for mitigating the vulnerability."
    validations:
      required: false
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: "Before submitting your vulnerability report, please ensure you have:"
      options:
        - label: "Reviewed the repository's SECURITY.md for reporting procedures."
        - label: "Consulted the CONTRIBUTING.md for additional guidelines."
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## Contact
        This repository is owned and maintained by **Md Asaduzzaman Atik**. If you have any questions or need further assistance, please reach out via:
        - **Casual Conversations:**  
          **Email:** [hey@mr.asadatik.dev](mailto:hey@mr.asadatik.dev)  
          For informal discussions, brainstorming, or sharing ideas.
        - **Professional Conversations & Networking:**  
          **Email:** [engage@mr.asadatik.dev](mailto:engage@mr.asadatik.dev)  
          For business discussions, networking, or professional opportunities.
        - **Career Development & Collaboration:**  
          **Email:** [flow@mr.asadatik.dev](mailto:flow@mr.asadatik.dev)  
          To discuss career paths, collaboration opportunities, or new projects.
        - **Support & Troubleshooting:**  
          **Email:** [help@mr.asadatik.dev](mailto:help@mr.asadatik.dev)  
          For project-related issues or technical support inquiries — I'm here to assist.
